import { db } from "./db";
import { attractions, restaurants, accommodations, tours, events, venues } from "../drizzle/schema";

/**
 * Comprehensive Cotswolds seed data
 * Populates database with real Cotswolds attractions, restaurants, hotels, tours, events, and venues
 */

async function seed() {
  console.log("🌾 Starting Cotswolds database seed...");

  // Clear existing data
  console.log("Clearing existing data...");
  await db.delete(attractions);
  await db.delete(restaurants);
  await db.delete(accommodations);
  await db.delete(tours);
  await db.delete(events);
  await db.delete(venues);

  // Seed Attractions
  console.log("Seeding attractions...");
  await db.insert(attractions).values([
    {
      name: "Blenheim Palace",
      slug: "blenheim-palace",
      description: "A UNESCO World Heritage Site and birthplace of Sir Winston Churchill. This magnificent baroque palace is set in over 2,000 acres of parkland landscaped by 'Capability' Brown. Explore the State Rooms, Churchill Exhibition, formal gardens, and adventure playground.",
      category: "Historic Sites",
      address: "Woodstock, Oxfordshire OX20 1PP",
      latitude: "51.8412",
      longitude: "-1.3617",
      imageUrl: "/images/manor-house.jpg",
      openingHours: "Daily 10:00 AM - 5:30 PM (seasonal variations apply)",
      pricing: "Adults £32, Children £19, Family £82",
      website: "https://www.blenheimpalace.com",
      phone: "01993 810530",
      featured: true,
    },
    {
      name: "Bibury Village",
      slug: "bibury-village",
      description: "Often described as the most beautiful village in England, Bibury is famous for Arlington Row, a stunning collection of 17th-century weavers' cottages. Stroll along the River Coln, visit the Bibury Trout Farm, and explore the charming honey-stone architecture.",
      category: "Villages",
      address: "Bibury, Gloucestershire GL7 5NP",
      latitude: "51.7656",
      longitude: "-1.8173",
      imageUrl: "/images/honey-stone-village.jpg",
      openingHours: "Open year-round",
      pricing: "Free to explore",
      website: "https://www.bibury.com",
      featured: true,
    },
    {
      name: "Bourton-on-the-Water",
      slug: "bourton-on-the-water",
      description: "Known as the 'Venice of the Cotswolds', this picturesque village features low bridges over the River Windrush. Visit the Cotswold Motoring Museum, Birdland Park & Gardens, and the Model Village. Perfect for families with plenty of cafes and shops.",
      category: "Villages",
      address: "Bourton-on-the-Water, Gloucestershire GL54 2AN",
      latitude: "51.8861",
      longitude: "-1.7603",
      imageUrl: "/images/cotswolds-hero.jpg",
      openingHours: "Open year-round",
      pricing: "Free to explore (individual attractions have fees)",
      website: "https://www.bourtoninfo.com",
      featured: true,
    },
    {
      name: "Castle Combe",
      slug: "castle-combe",
      description: "One of the prettiest villages in England with a picture-perfect main street lined with honey-colored stone cottages. This unspoiled medieval village has been used as a filming location for movies including War Horse and Stardust.",
      category: "Villages",
      address: "Castle Combe, Wiltshire SN14 7HN",
      latitude: "51.4918",
      longitude: "-2.2114",
      imageUrl: "/images/honey-stone-village.jpg",
      openingHours: "Open year-round",
      pricing: "Free to explore",
      featured: true,
    },
    {
      name: "Cotswold Wildlife Park and Gardens",
      slug: "cotswold-wildlife-park",
      description: "Set in 160 acres of landscaped parkland surrounding a Victorian manor house, this award-winning wildlife park is home to over 260 different species. See rhinos, giraffes, lions, penguins, and more. Beautiful gardens and adventure playground included.",
      category: "Family Friendly",
      address: "Burford, Oxfordshire OX18 4JP",
      latitude: "51.7814",
      longitude: "-1.6353",
      imageUrl: "/images/countryside-walk.jpg",
      openingHours: "Daily 10:00 AM - 6:00 PM (last entry 4:30 PM)",
      pricing: "Adults £18, Children £12.50, Family £55",
      website: "https://www.cotswoldwildlifepark.co.uk",
      phone: "01993 823006",
      featured: true,
    },
    {
      name: "Sudeley Castle & Gardens",
      slug: "sudeley-castle",
      description: "A magnificent castle with royal connections spanning 1,000 years. Once home to Queen Katherine Parr, the castle features award-winning gardens, exhibitions, and stunning architecture. Explore the State Rooms, Pheasantry, and beautiful grounds.",
      category: "Historic Sites",
      address: "Winchcombe, Cheltenham GL54 5JD",
      latitude: "51.9553",
      longitude: "-1.9503",
      imageUrl: "/images/manor-house.jpg",
      openingHours: "Daily 10:00 AM - 5:00 PM (March-October)",
      pricing: "Adults £19.50, Children £10, Family £52",
      website: "https://www.sudeleycastle.co.uk",
      phone: "01242 604244",
    },
    {
      name: "Gloucester Cathedral",
      slug: "gloucester-cathedral",
      description: "A stunning medieval cathedral with breathtaking Gothic architecture. Famous as a filming location for Harry Potter, the cathedral features magnificent cloisters, beautiful stained glass, and the tomb of King Edward II. Guided tours available.",
      category: "Historic Sites",
      address: "12 College Green, Gloucester GL1 2LX",
      latitude: "51.8670",
      longitude: "-2.2467",
      imageUrl: "/images/manor-house.jpg",
      openingHours: "Daily 7:30 AM - 6:00 PM",
      pricing: "Free entry (donations welcome), Tower tours £8",
      website: "https://www.gloucestercathedral.org.uk",
      phone: "01452 528095",
    },
    {
      name: "Lower Slaughter",
      slug: "lower-slaughter",
      description: "An idyllic Cotswold village with picture-perfect limestone cottages lining the banks of the River Eye. Explore the Old Mill, walk along the riverside path, and enjoy the quintessential English countryside charm. Connected to Upper Slaughter by a scenic footpath.",
      category: "Villages",
      address: "Lower Slaughter, Gloucestershire GL54 2HP",
      latitude: "51.9244",
      longitude: "-1.7667",
      imageUrl: "/images/honey-stone-village.jpg",
      openingHours: "Open year-round",
      pricing: "Free to explore",
      featured: true,
    },
    {
      name: "Hidcote Manor Garden",
      slug: "hidcote-manor-garden",
      description: "One of England's great gardens, created by Lawrence Johnston in the early 20th century. This Arts and Crafts masterpiece features a series of outdoor 'rooms' with rare plants, stunning borders, and beautiful vistas. National Trust property.",
      category: "Gardens & Nature",
      address: "Hidcote Bartrim, Chipping Campden GL55 6LR",
      latitude: "52.0581",
      longitude: "-1.7431",
      imageUrl: "/images/countryside-walk.jpg",
      openingHours: "Daily 10:00 AM - 5:00 PM (seasonal variations)",
      pricing: "Adults £14.50, Children £7.25, Family £36.25",
      website: "https://www.nationaltrust.org.uk/hidcote",
      phone: "01386 438333",
    },
    {
      name: "Cirencester",
      slug: "cirencester",
      description: "Known as the 'Capital of the Cotswolds', this historic market town was once the second-largest city in Roman Britain. Visit the Corinium Museum, explore the Roman Amphitheatre, shop at the twice-weekly market, and enjoy the vibrant town center.",
      category: "Towns",
      address: "Cirencester, Gloucestershire GL7 2BX",
      latitude: "51.7194",
      longitude: "-1.9708",
      imageUrl: "/images/honey-stone-village.jpg",
      openingHours: "Open year-round",
      pricing: "Free to explore (museum entry £6.50)",
      website: "https://www.cirencester.co.uk",
    },
    {
      name: "Stow-on-the-Wold",
      slug: "stow-on-the-wold",
      description: "A charming market town perched on a hilltop with a historic market square surrounded by antique shops, galleries, and cozy pubs. Famous for its twice-yearly horse fairs and as a center for antiques. Explore the narrow alleyways and independent shops.",
      category: "Towns",
      address: "Stow-on-the-Wold, Gloucestershire GL54 1AB",
      latitude: "51.9308",
      longitude: "-1.7253",
      imageUrl: "/images/honey-stone-village.jpg",
      openingHours: "Open year-round",
      pricing: "Free to explore",
    },
    {
      name: "Burford",
      slug: "burford",
      description: "A beautiful medieval town with a steep main street lined with honey-stone buildings, antique shops, and tea rooms. Known as the 'Gateway to the Cotswolds', Burford features a magnificent church, historic bridges, and charming alleyways to explore.",
      category: "Towns",
      address: "Burford, Oxfordshire OX18 4SN",
      latitude: "51.8078",
      longitude: "-1.6372",
      imageUrl: "/images/honey-stone-village.jpg",
      openingHours: "Open year-round",
      pricing: "Free to explore",
    },
    {
      name: "Birdland Park & Gardens",
      slug: "birdland-park",
      description: "A delightful bird park set in nine acres of gardens and woodland in Bourton-on-the-Water. Home to over 500 birds including penguins, flamingos, pelicans, and parrots. Daily penguin feeding shows and beautiful riverside setting.",
      category: "Family Friendly",
      address: "Rissington Road, Bourton-on-the-Water GL54 2BN",
      latitude: "51.8872",
      longitude: "-1.7539",
      imageUrl: "/images/countryside-walk.jpg",
      openingHours: "Daily 10:00 AM - 6:00 PM (April-October), 10:00 AM - 4:00 PM (November-March)",
      pricing: "Adults £12.50, Children £8.50, Family £40",
      website: "https://www.birdland.co.uk",
      phone: "01451 820480",
    },
    {
      name: "Cotswold Farm Park",
      slug: "cotswold-farm-park",
      description: "Founded by rare breed conservation pioneer Joe Henson, this working farm offers hands-on animal experiences. Meet rare breed sheep, pigs, cattle, and poultry. Features adventure playgrounds, tractor rides, and seasonal lambing events.",
      category: "Family Friendly",
      address: "Guiting Power, Cheltenham GL54 5UG",
      latitude: "51.9483",
      longitude: "-1.8467",
      imageUrl: "/images/countryside-walk.jpg",
      openingHours: "Daily 10:00 AM - 5:00 PM (seasonal)",
      pricing: "Adults £14.95, Children £12.95, Family £52",
      website: "https://www.cotswoldfarmpark.co.uk",
      phone: "01451 850307",
    },
    {
      name: "Chipping Campden",
      slug: "chipping-campden",
      description: "One of the finest medieval wool towns in England with a magnificent High Street of honey-colored limestone buildings. Visit the historic Market Hall, St James' Church, and explore the many craft workshops and galleries. Starting point for Cotswold Way.",
      category: "Towns",
      address: "Chipping Campden, Gloucestershire GL55 6AT",
      latitude: "52.0414",
      longitude: "-1.7803",
      imageUrl: "/images/honey-stone-village.jpg",
      openingHours: "Open year-round",
      pricing: "Free to explore",
    },
  ]);

  // Seed Restaurants
  console.log("Seeding restaurants...");
  await db.insert(restaurants).values([
    {
      name: "The Wild Rabbit",
      slug: "the-wild-rabbit",
      description: "A stylish country inn in the heart of the Cotswolds serving seasonal British cuisine. Owned by Daylesford Organic, this Michelin-recommended restaurant offers farm-to-table dining in a relaxed, contemporary setting. Beautiful rooms available for overnight stays.",
      cuisine: "Modern British",
      address: "Church Street, Kingham, Oxfordshire OX7 6YA",
      latitude: "51.9156",
      longitude: "-1.6222",
      priceRange: "£££",
      imageUrl: "/images/traditional-pub.jpg",
      website: "https://www.thewildrabbit.co.uk",
      phone: "01608 658389",
      featured: true,
    },
    {
      name: "The Kingham Plough",
      slug: "the-kingham-plough",
      description: "A Michelin-starred gastropub offering exceptional modern British cuisine in a cozy village setting. Chef Emily Watkins creates innovative dishes using local and seasonal ingredients. Warm atmosphere with open fires and a carefully curated wine list.",
      cuisine: "Modern British",
      address: "The Green, Kingham, Oxfordshire OX7 6YD",
      latitude: "51.9167",
      longitude: "-1.6239",
      priceRange: "£££",
      imageUrl: "/images/traditional-pub.jpg",
      website: "https://www.thekinghamplough.co.uk",
      phone: "01608 658327",
      featured: true,
    },
    {
      name: "The Lamb Inn",
      slug: "the-lamb-inn-burford",
      description: "A charming 15th-century coaching inn in the heart of Burford. This traditional Cotswold pub offers classic British fare, real ales, and comfortable accommodation. Beautiful walled garden for summer dining and cozy fireplaces for winter.",
      cuisine: "Traditional British",
      address: "Sheep Street, Burford, Oxfordshire OX18 4LR",
      latitude: "51.8089",
      longitude: "-1.6378",
      priceRange: "££",
      imageUrl: "/images/traditional-pub.jpg",
      website: "https://www.cotswold-inns-hotels.co.uk/the-lamb-inn",
      phone: "01993 823155",
      featured: true,
    },
    {
      name: "The Feathered Nest Country Inn",
      slug: "the-feathered-nest",
      description: "A stunning country inn with panoramic Cotswold views. Michelin-recommended restaurant serving refined British cuisine with French influences. Luxurious rooms, extensive wine cellar, and beautiful terraced gardens. Perfect for special occasions.",
      cuisine: "Modern British",
      address: "Nether Westcote, Chipping Norton OX7 6SD",
      latitude: "51.8944",
      longitude: "-1.6556",
      priceRange: "£££",
      imageUrl: "/images/traditional-pub.jpg",
      website: "https://www.thefeatherednestinn.co.uk",
      phone: "01993 833030",
      featured: true,
    },
    {
      name: "The King's Head Inn",
      slug: "the-kings-head-inn",
      description: "Multiple winner of The Good Pub Guide Pub of the Year, this quintessential Cotswolds pub sits on the village green in Bledington. Serves excellent traditional pub food, real ales, and has a beautiful garden. Charming rooms available.",
      cuisine: "Traditional British",
      address: "The Green, Bledington, Oxfordshire OX7 6XQ",
      latitude: "51.9153",
      longitude: "-1.6781",
      priceRange: "££",
      imageUrl: "/images/traditional-pub.jpg",
      website: "https://www.kingsheadinn.net",
      phone: "01608 658365",
    },
    {
      name: "The Bell at Stow",
      slug: "the-bell-at-stow",
      description: "A historic coaching inn in the heart of Stow-on-the-Wold offering contemporary British cuisine in elegant surroundings. Features a beautiful courtyard garden, stylish bar, and comfortable boutique rooms. Perfect location for exploring the Cotswolds.",
      cuisine: "Modern British",
      address: "Park Street, Stow-on-the-Wold GL54 1AF",
      latitude: "51.9311",
      longitude: "-1.7258",
      priceRange: "££",
      imageUrl: "/images/traditional-pub.jpg",
      website: "https://www.thebellatstow.com",
      phone: "01451 870916",
    },
    {
      name: "The Fox Inn",
      slug: "the-fox-inn-broadwell",
      description: "A traditional Cotswold stone pub in the picturesque village of Broadwell. Serves hearty British classics, local ales, and has a welcoming atmosphere. Beautiful beer garden and dog-friendly. Popular with walkers and locals alike.",
      cuisine: "Traditional British",
      address: "Broadwell, Moreton-in-Marsh GL56 0UF",
      latitude: "51.9722",
      longitude: "-1.7356",
      priceRange: "££",
      imageUrl: "/images/traditional-pub.jpg",
      website: "https://www.thefoxinnbroadwell.com",
      phone: "01451 870909",
    },
    {
      name: "The Old Bakery Tearoom",
      slug: "the-old-bakery-tearoom",
      description: "A delightful tearoom in the charming village of Blockley. Serves homemade cakes, traditional afternoon tea, light lunches, and excellent coffee. Cozy interior with a lovely garden. Perfect for a relaxing break while exploring the Cotswolds.",
      cuisine: "Cafe & Tearoom",
      address: "High Street, Blockley, Moreton-in-Marsh GL56 9EX",
      latitude: "52.0058",
      longitude: "-1.7542",
      priceRange: "£",
      imageUrl: "/images/traditional-pub.jpg",
      website: "https://www.theoldbakeryblockley.co.uk",
      phone: "01386 700408",
    },
    {
      name: "The Painswick",
      slug: "the-painswick",
      description: "A stylish boutique hotel and restaurant in the beautiful village of Painswick. Serves modern British cuisine with Mediterranean influences. Beautiful views over the Slad Valley, elegant interiors, and a relaxed atmosphere. Excellent wine selection.",
      cuisine: "Modern British",
      address: "Kemps Lane, Painswick, Gloucestershire GL6 6YB",
      latitude: "51.7836",
      longitude: "-2.1906",
      priceRange: "£££",
      imageUrl: "/images/traditional-pub.jpg",
      website: "https://www.thepainswick.co.uk",
      phone: "01452 813688",
    },
    {
      name: "The Pig in the Cotswolds",
      slug: "the-pig-cotswolds",
      description: "Part of the award-winning Pig Hotels group, this beautiful country house hotel near Barnsley offers 25-mile menu dining. Ingredients sourced from the kitchen garden and local suppliers. Rustic-chic interiors, cozy lounges, and beautiful grounds.",
      cuisine: "Modern British",
      address: "Barnsley House, Barnsley, Cirencester GL7 5EE",
      latitude: "51.7631",
      longitude: "-1.8717",
      priceRange: "£££",
      imageUrl: "/images/traditional-pub.jpg",
      website: "https://www.thepighotel.com/in-the-cotswolds",
      phone: "01285 740000",
      featured: true,
    },
    {
      name: "The Chequers",
      slug: "the-chequers-churchill",
      description: "A charming village pub in Churchill serving excellent food and local ales. Warm and welcoming atmosphere with open fires, traditional decor, and a beautiful garden. Menu features British classics made with local ingredients. Dog-friendly.",
      cuisine: "Traditional British",
      address: "Church Road, Churchill, Chipping Norton OX7 6NJ",
      latitude: "51.9167",
      longitude: "-1.5833",
      priceRange: "££",
      imageUrl: "/images/traditional-pub.jpg",
      phone: "01608 659393",
    },
    {
      name: "Smiths of Bourton",
      slug: "smiths-of-bourton",
      description: "A contemporary restaurant and cocktail bar in Bourton-on-the-Water. Serves modern British cuisine with international influences. Stylish interior, riverside location, and creative cocktails. Popular for brunch, lunch, and dinner.",
      cuisine: "Modern British",
      address: "Riverside, Bourton-on-the-Water GL54 2BN",
      latitude: "51.8856",
      longitude: "-1.7589",
      priceRange: "££",
      imageUrl: "/images/traditional-pub.jpg",
      website: "https://www.smithsofbourton.co.uk",
      phone: "01451 822658",
    },
  ]);

  // Seed Accommodations
  console.log("Seeding accommodations...");
  await db.insert(accommodations).values([
    {
      name: "The Slaughters Manor House",
      slug: "the-slaughters-manor-house",
      description: "A luxurious 5-star country house hotel set in 17th-century manor house in Lower Slaughter. Features elegant rooms and suites, award-winning restaurant, spa, and beautiful gardens. Perfect for romantic getaways and special occasions.",
      type: "Luxury Hotel",
      address: "Copsehill Road, Lower Slaughter GL54 2HP",
      latitude: "51.9239",
      longitude: "-1.7672",
      priceRange: "££££",
      imageUrl: "/images/manor-house.jpg",
      bookingUrl: "https://www.slaughtersmanor.co.uk",
      phone: "01451 820456",
      featured: true,
    },
    {
      name: "Lords of the Manor",
      slug: "lords-of-the-manor",
      description: "An exquisite country house hotel in Upper Slaughter with Michelin-starred dining. Set in 8 acres of gardens with beautiful views. Luxurious rooms, exceptional service, and fine dining. Perfect for a luxury Cotswolds escape.",
      type: "Luxury Hotel",
      address: "Upper Slaughter, Cheltenham GL54 2JD",
      latitude: "51.9303",
      longitude: "-1.7639",
      priceRange: "££££",
      imageUrl: "/images/manor-house.jpg",
      bookingUrl: "https://www.lordsofthemanor.com",
      phone: "01451 820243",
      featured: true,
    },
    {
      name: "Ellenborough Park",
      slug: "ellenborough-park",
      description: "A magnificent 5-star hotel set in a 15th-century manor house near Cheltenham Racecourse. Features luxurious rooms, spa, indoor and outdoor pools, and fine dining. Beautiful grounds with views of the Cotswold escarpment.",
      type: "Luxury Hotel",
      address: "Southam Road, Cheltenham GL52 3NJ",
      latitude: "51.9333",
      longitude: "-2.0667",
      priceRange: "££££",
      imageUrl: "/images/manor-house.jpg",
      bookingUrl: "https://www.ellenboroughpark.com",
      phone: "01242 545454",
      featured: true,
    },
    {
      name: "The Lygon Arms",
      slug: "the-lygon-arms",
      description: "A historic luxury hotel in the heart of Broadway dating back to 1532. Features elegant rooms, spa, fine dining, and beautiful gardens. Rich history with period features combined with modern luxury. Perfect Cotswolds base.",
      type: "Luxury Hotel",
      address: "High Street, Broadway WR12 7DU",
      latitude: "52.0333",
      longitude: "-1.8667",
      priceRange: "£££",
      imageUrl: "/images/manor-house.jpg",
      bookingUrl: "https://www.lygonarmshotel.co.uk",
      phone: "01386 852255",
    },
    {
      name: "No.38 The Park",
      slug: "no-38-the-park",
      description: "A stylish boutique hotel in Cheltenham with contemporary design and excellent service. Features beautifully designed rooms, award-winning restaurant, and a central location. Perfect for exploring the Cotswolds and Cheltenham.",
      type: "Boutique Hotel",
      address: "38 Evesham Road, Cheltenham GL52 2AH",
      latitude: "51.8989",
      longitude: "-2.0753",
      priceRange: "£££",
      imageUrl: "/images/manor-house.jpg",
      bookingUrl: "https://www.no38thepark.com",
      phone: "01242 822929",
    },
    {
      name: "Cotswold House Hotel & Spa",
      slug: "cotswold-house-hotel",
      description: "A luxury boutique hotel in the heart of Chipping Campden. Features elegant rooms, award-winning spa, fine dining restaurant, and beautiful gardens. Regency townhouse with modern amenities and exceptional service.",
      type: "Boutique Hotel",
      address: "The Square, Chipping Campden GL55 6AN",
      latitude: "52.0417",
      longitude: "-1.7806",
      priceRange: "£££",
      imageUrl: "/images/manor-house.jpg",
      bookingUrl: "https://www.cotswoldhouse.com",
      phone: "01386 840330",
    },
    {
      name: "The Fish Hotel",
      slug: "the-fish-hotel",
      description: "A unique luxury retreat near Broadway with 66 rooms, suites, huts, and treehouses. Set in beautiful countryside with Cotswold views. Features restaurant, bar, and outdoor activities. Perfect for families and couples seeking something different.",
      type: "Boutique Hotel",
      address: "Farncombe Estate, Broadway WR12 7LJ",
      latitude: "52.0167",
      longitude: "-1.8833",
      priceRange: "£££",
      imageUrl: "/images/countryside-walk.jpg",
      bookingUrl: "https://www.thefishhotel.co.uk",
      phone: "01386 858000",
    },
    {
      name: "Number Four at Stow",
      slug: "number-four-at-stow",
      description: "A charming boutique hotel and restaurant in the heart of Stow-on-the-Wold. Features individually designed rooms, excellent restaurant, and warm hospitality. Perfect location for exploring the Cotswolds with antique shops and pubs nearby.",
      type: "Boutique Hotel",
      address: "Fosseway, Stow-on-the-Wold GL54 1JX",
      latitude: "51.9314",
      longitude: "-1.7247",
      priceRange: "££",
      imageUrl: "/images/honey-stone-village.jpg",
      bookingUrl: "https://www.hotelnumberfour.co.uk",
      phone: "01451 830297",
    },
    {
      name: "The Swan Hotel",
      slug: "the-swan-bibury",
      description: "A beautiful country hotel in the heart of Bibury, one of England's prettiest villages. Features comfortable rooms, riverside location, traditional restaurant, and cozy bar. Perfect base for exploring the Cotswolds.",
      type: "Country Hotel",
      address: "Bibury, Cirencester GL7 5NW",
      latitude: "51.7658",
      longitude: "-1.8178",
      priceRange: "£££",
      imageUrl: "/images/honey-stone-village.jpg",
      bookingUrl: "https://www.swanhotel.co.uk",
      phone: "01285 740695",
    },
    {
      name: "The Rectory Hotel",
      slug: "the-rectory-hotel",
      description: "A stylish boutique hotel in the beautiful village of Crudwell. Features elegant rooms, award-winning restaurant, and beautiful gardens. Former rectory with period features and modern luxury. Excellent base for Cotswolds exploration.",
      type: "Boutique Hotel",
      address: "Crudwell, Malmesbury SN16 9EP",
      latitude: "51.6167",
      longitude: "-2.0833",
      priceRange: "£££",
      imageUrl: "/images/manor-house.jpg",
      bookingUrl: "https://www.therectoryhotel.com",
      phone: "01666 577194",
    },
    {
      name: "The Old Stocks Inn",
      slug: "the-old-stocks-inn",
      description: "A historic boutique hotel in the center of Stow-on-the-Wold. Features beautifully designed rooms, excellent restaurant, and cozy bar. Named after the medieval stocks that still stand on the village green opposite. Perfect Cotswolds location.",
      type: "Boutique Hotel",
      address: "The Square, Stow-on-the-Wold GL54 1AF",
      latitude: "51.9308",
      longitude: "-1.7253",
      priceRange: "££",
      imageUrl: "/images/honey-stone-village.jpg",
      bookingUrl: "https://www.oldstocksinn.com",
      phone: "01451 830666",
    },
    {
      name: "The Porch House",
      slug: "the-porch-house",
      description: "England's oldest inn dating back to 947 AD, located in Stow-on-the-Wold. Features historic rooms with modern comforts, excellent restaurant, and traditional pub. Rich history combined with contemporary luxury and warm hospitality.",
      type: "Historic Inn",
      address: "Digbeth Street, Stow-on-the-Wold GL54 1BN",
      latitude: "51.9303",
      longitude: "-1.7261",
      priceRange: "££",
      imageUrl: "/images/honey-stone-village.jpg",
      bookingUrl: "https://www.porch-house.co.uk",
      phone: "01451 870048",
    },
  ]);

  // Seed Tours
  console.log("Seeding tours...");
  await db.insert(tours).values([
    {
      name: "Cotswolds Village Discovery Tour",
      slug: "village-discovery-tour",
      description: "Explore the most beautiful villages of the Cotswolds including Bibury, Bourton-on-the-Water, and the Slaughters. Visit honey-stone cottages, historic churches, and picturesque riverside settings. Small group tour with expert local guide. Includes village walks and photo opportunities.",
      duration: "Full day (8 hours)",
      price: "From £85 per person",
      imageUrl: "/images/honey-stone-village.jpg",
      bookingUrl: "https://www.bestcotswoldtours.co.uk",
      featured: true,
    },
    {
      name: "Cotswold Way Walking Tour",
      slug: "cotswold-way-walking",
      description: "Self-guided or guided walking tour along the famous Cotswold Way National Trail. Experience stunning countryside views, rolling hills, and charming villages. Choose from 3-day to 7-day itineraries. Luggage transfer and accommodation included.",
      duration: "3-7 days",
      price: "From £495 per person",
      imageUrl: "/images/countryside-walk.jpg",
      bookingUrl: "https://www.cotswoldwalks.com",
      featured: true,
    },
    {
      name: "Cotswolds Food & Drink Tour",
      slug: "food-drink-tour",
      description: "Discover the culinary delights of the Cotswolds. Visit local producers, farm shops, breweries, and distilleries. Enjoy tastings of artisan cheese, local ales, gin, and traditional foods. Includes lunch at a gastropub. Small group experience.",
      duration: "Half day (4 hours)",
      price: "From £75 per person",
      imageUrl: "/images/traditional-pub.jpg",
      bookingUrl: "https://www.cotswoldtoursandtravel.com",
      featured: true,
    },
    {
      name: "Blenheim Palace & Cotswolds Tour",
      slug: "blenheim-palace-tour",
      description: "Visit the magnificent UNESCO World Heritage Site of Blenheim Palace, birthplace of Winston Churchill. Explore the State Rooms, Churchill Exhibition, and beautiful gardens. Continue to nearby Cotswold villages. Full day tour with expert guide.",
      duration: "Full day (8 hours)",
      price: "From £95 per person (palace entry included)",
      imageUrl: "/images/manor-house.jpg",
      bookingUrl: "https://www.bestcotswoldtours.co.uk",
    },
    {
      name: "Cotswolds Photography Tour",
      slug: "photography-tour",
      description: "Capture the beauty of the Cotswolds with a professional photographer guide. Visit the most photogenic villages and landscapes at golden hour. Learn photography techniques and discover hidden gems. Small group tour with personalized instruction.",
      duration: "Full day (8 hours)",
      price: "From £125 per person",
      imageUrl: "/images/cotswolds-hero.jpg",
      bookingUrl: "https://www.cotswoldtoursandtravel.com",
    },
    {
      name: "Private Luxury Cotswolds Tour",
      slug: "private-luxury-tour",
      description: "Fully customizable private tour of the Cotswolds with chauffeur guide. Visit villages, attractions, and restaurants of your choice. Luxury vehicle, flexible itinerary, and personalized service. Perfect for couples, families, or small groups.",
      duration: "Flexible (4-8 hours)",
      price: "From £450 per vehicle",
      imageUrl: "/images/cotswolds-hero.jpg",
      bookingUrl: "https://www.cotswoldtoursandtravel.com",
      featured: true,
    },
    {
      name: "Cotswolds E-Bike Tour",
      slug: "e-bike-tour",
      description: "Explore the Cotswolds countryside on an electric bike. Cycle through villages, along quiet country lanes, and enjoy stunning views without the effort. E-bikes, helmets, and route maps provided. Self-guided or guided options available.",
      duration: "Half day or full day",
      price: "From £45 per person",
      imageUrl: "/images/countryside-walk.jpg",
      bookingUrl: "https://www.wildernessengland.com",
    },
    {
      name: "Cotswolds Gardens Tour",
      slug: "gardens-tour",
      description: "Visit the finest gardens of the Cotswolds including Hidcote Manor, Kiftsgate Court, and Sudeley Castle Gardens. Explore Arts and Crafts gardens, historic landscapes, and beautiful plantings. Expert garden guide and entrance fees included.",
      duration: "Full day (7 hours)",
      price: "From £95 per person",
      imageUrl: "/images/countryside-walk.jpg",
      bookingUrl: "https://www.cotswoldjourneys.com",
    },
    {
      name: "Cotswolds Market Towns Tour",
      slug: "market-towns-tour",
      description: "Discover the historic market towns of the Cotswolds including Stow-on-the-Wold, Chipping Campden, and Moreton-in-Marsh. Visit antique shops, local markets, and historic buildings. Includes free time for shopping and lunch.",
      duration: "Full day (8 hours)",
      price: "From £80 per person",
      imageUrl: "/images/honey-stone-village.jpg",
      bookingUrl: "https://www.activeenglandtours.com",
    },
    {
      name: "Cotswolds Wildlife & Nature Tour",
      slug: "wildlife-nature-tour",
      description: "Explore the natural beauty and wildlife of the Cotswolds. Visit Cotswold Wildlife Park, nature reserves, and scenic walking trails. Learn about local flora and fauna with an expert naturalist guide. Perfect for families and nature lovers.",
      duration: "Full day (7 hours)",
      price: "From £85 per person (park entry included)",
      imageUrl: "/images/countryside-walk.jpg",
      bookingUrl: "https://www.cotswoldjourneys.com",
    },
  ]);

  // Seed Events
  console.log("Seeding events...");
  await db.insert(events).values([
    {
      title: "Cheltenham Jazz Festival",
      slug: "cheltenham-jazz-festival",
      description: "One of the UK's leading jazz festivals featuring world-class musicians, emerging talent, and diverse jazz styles. Enjoy concerts, workshops, and late-night sessions across multiple venues in Cheltenham. A celebration of jazz in all its forms.",
      category: "Festival",
      startDate: new Date("2025-04-29"),
      endDate: new Date("2025-05-04"),
      location: "Various venues, Cheltenham",
      imageUrl: "/images/cotswolds-hero.jpg",
      ticketUrl: "https://www.cheltenhamfestivals.com/jazz",
      price: "From £20",
      featured: true,
    },
    {
      title: "Cheltenham Literature Festival",
      slug: "cheltenham-literature-festival",
      description: "The world's oldest literature festival featuring renowned authors, poets, and thinkers. Enjoy talks, debates, workshops, and book signings. A celebration of words and ideas in the heart of the Cotswolds.",
      category: "Festival",
      startDate: new Date("2025-10-03"),
      endDate: new Date("2025-10-12"),
      location: "Various venues, Cheltenham",
      imageUrl: "/images/honey-stone-village.jpg",
      ticketUrl: "https://www.cheltenhamfestivals.com/literature",
      price: "From £15",
      featured: true,
    },
    {
      title: "Cheltenham Gold Cup",
      slug: "cheltenham-gold-cup",
      description: "The pinnacle of National Hunt racing featuring the prestigious Gold Cup race. Four days of world-class horse racing, fashion, and entertainment. The highlight of the racing calendar set in the beautiful Cotswolds.",
      category: "Sports",
      startDate: new Date("2025-03-11"),
      endDate: new Date("2025-03-14"),
      location: "Cheltenham Racecourse",
      imageUrl: "/images/countryside-walk.jpg",
      ticketUrl: "https://www.cheltenham.co.uk",
      price: "From £35",
      featured: true,
    },
    {
      title: "Wilderness Festival",
      slug: "wilderness-festival",
      description: "A unique outdoor festival combining music, arts, food, and wellness in the beautiful Cotswolds countryside. Features live music, theatre, spa treatments, wild swimming, and gourmet dining. A celebration of culture and nature.",
      category: "Festival",
      startDate: new Date("2025-08-07"),
      endDate: new Date("2025-08-10"),
      location: "Cornbury Park, Oxfordshire",
      imageUrl: "/images/countryside-walk.jpg",
      ticketUrl: "https://www.wildernessfestival.com",
      price: "From £225",
      featured: true,
    },
    {
      title: "Cirencester Antiques Market",
      slug: "cirencester-antiques-market",
      description: "Browse hundreds of stalls selling antiques, collectables, vintage items, and curiosities. One of the largest antiques markets in the Cotswolds. Perfect for treasure hunters and collectors. Held monthly in the historic market town.",
      category: "Market",
      startDate: new Date("2025-01-13"),
      endDate: new Date("2025-01-13"),
      location: "Corn Hall, Cirencester",
      imageUrl: "/images/honey-stone-village.jpg",
      price: "Free entry",
    },
    {
      title: "Moreton-in-Marsh Market",
      slug: "moreton-market",
      description: "Traditional weekly market in the heart of Moreton-in-Marsh. Browse stalls selling fresh produce, local crafts, clothing, and household goods. A Cotswolds tradition dating back centuries. Every Tuesday, rain or shine.",
      category: "Market",
      startDate: new Date("2025-01-07"),
      endDate: new Date("2025-12-30"),
      location: "High Street, Moreton-in-Marsh",
      imageUrl: "/images/honey-stone-village.jpg",
      price: "Free entry",
    },
    {
      title: "Gloucester History Festival",
      slug: "gloucester-history-festival",
      description: "A celebration of Gloucester's rich history with talks, tours, exhibitions, and reenactments. Explore the city's Roman, medieval, and Victorian heritage. Activities for all ages including cathedral tours and historical walks.",
      category: "Festival",
      startDate: new Date("2025-09-06"),
      endDate: new Date("2025-09-14"),
      location: "Various venues, Gloucester",
      imageUrl: "/images/manor-house.jpg",
      ticketUrl: "https://www.gloucesterhistoryfestival.co.uk",
      price: "Many free events",
    },
    {
      title: "Chipping Campden Music Festival",
      slug: "chipping-campden-music",
      description: "A week-long festival of classical music in the beautiful setting of Chipping Campden. Features concerts, recitals, and chamber music performances in historic venues. Showcasing established and emerging musicians.",
      category: "Festival",
      startDate: new Date("2025-05-10"),
      endDate: new Date("2025-05-17"),
      location: "Various venues, Chipping Campden",
      imageUrl: "/images/honey-stone-village.jpg",
      ticketUrl: "https://www.campdenmusicfestival.co.uk",
      price: "From £15",
    },
    {
      title: "Winchcombe Walking Festival",
      slug: "winchcombe-walking-festival",
      description: "A celebration of walking in the Cotswolds with guided walks for all abilities. Explore the beautiful countryside, historic sites, and charming villages around Winchcombe. Expert guides share local knowledge and history.",
      category: "Festival",
      startDate: new Date("2025-05-17"),
      endDate: new Date("2025-05-25"),
      location: "Winchcombe and surrounding area",
      imageUrl: "/images/countryside-walk.jpg",
      ticketUrl: "https://www.winchcombewelcomeswalkers.com",
      price: "From £5 per walk",
    },
    {
      title: "Cotswold Show & Food Festival",
      slug: "cotswold-show",
      description: "The premier agricultural show in the Cotswolds featuring livestock competitions, rural crafts, food and drink producers, and countryside activities. A celebration of rural life with entertainment for all the family.",
      category: "Festival",
      startDate: new Date("2025-07-12"),
      endDate: new Date("2025-07-13"),
      location: "Cirencester Park",
      imageUrl: "/images/countryside-walk.jpg",
      ticketUrl: "https://www.cotswoldshow.co.uk",
      price: "From £18",
    },
    {
      title: "Stroud Shambles Market",
      slug: "stroud-shambles",
      description: "A vibrant market held every Friday and Saturday featuring vintage items, antiques, collectables, local crafts, and street food. Browse unique finds in the atmospheric Shambles area of Stroud. A treasure trove for collectors.",
      category: "Market",
      startDate: new Date("2025-01-03"),
      endDate: new Date("2025-12-27"),
      location: "The Shambles, Stroud",
      imageUrl: "/images/honey-stone-village.jpg",
      price: "Free entry",
    },
    {
      title: "Cotswold Lavender Festival",
      slug: "lavender-festival",
      description: "Celebrate the lavender harvest with tours of the beautiful lavender fields, workshops, and shopping. Learn about lavender cultivation, enjoy refreshments, and purchase lavender products. A fragrant Cotswolds experience.",
      category: "Festival",
      startDate: new Date("2025-07-01"),
      endDate: new Date("2025-08-15"),
      location: "Cotswold Lavender, Snowshill",
      imageUrl: "/images/countryside-walk.jpg",
      ticketUrl: "https://www.cotswoldlavender.co.uk",
      price: "From £5",
    },
  ]);

  // Seed Venues
  console.log("Seeding venues...");
  await db.insert(venues).values([
    {
      name: "Ellenborough Park",
      slug: "ellenborough-park-venue",
      description: "A magnificent 5-star wedding and events venue set in a 15th-century manor house. Offers exclusive use packages, beautiful grounds, elegant reception rooms, and luxurious accommodation. Perfect for weddings, corporate events, and celebrations.",
      category: "Wedding",
      capacity: 150,
      address: "Southam Road, Cheltenham GL52 3NJ",
      latitude: "51.9333",
      longitude: "-2.0667",
      amenities: JSON.stringify(["Licensed for ceremonies", "Accommodation", "Spa", "Gardens", "Catering", "Event planning"]),
      pricing: "Wedding packages from £8,000",
      imageUrl: "/images/manor-house.jpg",
      website: "https://www.ellenboroughpark.com/weddings",
      phone: "01242 545454",
      email: "info@ellenboroughpark.com",
      featured: true,
    },
    {
      name: "Sudeley Castle",
      slug: "sudeley-castle-venue",
      description: "A historic castle with 1,000 years of royal connections, offering exclusive wedding and event packages. Features stunning State Rooms, award-winning gardens, and picturesque settings. Capacity for ceremonies and receptions up to 200 guests.",
      category: "Wedding",
      capacity: 200,
      address: "Winchcombe, Cheltenham GL54 5JD",
      latitude: "51.9553",
      longitude: "-1.9503",
      amenities: JSON.stringify(["Licensed for ceremonies", "Historic venue", "Gardens", "Exclusive use", "Catering", "Parking"]),
      pricing: "Wedding packages from £6,500",
      imageUrl: "/images/manor-house.jpg",
      website: "https://www.sudeleycastle.co.uk/weddings",
      phone: "01242 604244",
      email: "events@sudeley.org.uk",
      featured: true,
    },
    {
      name: "Barnsley House",
      slug: "barnsley-house-venue",
      description: "An intimate luxury wedding venue with beautiful gardens and elegant interiors. Part of the Pig Hotels group, offering exceptional food and service. Perfect for smaller weddings up to 80 guests. Romantic Cotswold stone setting.",
      category: "Wedding",
      capacity: 80,
      address: "Barnsley, Cirencester GL7 5EE",
      latitude: "51.7631",
      longitude: "-1.8717",
      amenities: JSON.stringify(["Licensed for ceremonies", "Gardens", "Accommodation", "Fine dining", "Exclusive use", "Wedding planning"]),
      pricing: "Wedding packages from £12,000",
      imageUrl: "/images/manor-house.jpg",
      website: "https://www.barnsleyhouse.com/weddings",
      phone: "01285 740000",
      email: "events@barnsleyhouse.com",
      featured: true,
    },
    {
      name: "Cotswold House Hotel & Spa",
      slug: "cotswold-house-venue",
      description: "A luxury boutique hotel in Chipping Campden offering elegant wedding and event spaces. Features beautiful gardens, spa facilities, and fine dining. Licensed for ceremonies with capacity for up to 120 guests. Exclusive use available.",
      category: "Wedding",
      capacity: 120,
      address: "The Square, Chipping Campden GL55 6AN",
      latitude: "52.0417",
      longitude: "-1.7806",
      amenities: JSON.stringify(["Licensed for ceremonies", "Spa", "Gardens", "Accommodation", "Catering", "Event coordination"]),
      pricing: "Wedding packages from £7,500",
      imageUrl: "/images/manor-house.jpg",
      website: "https://www.cotswoldhouse.com/weddings",
      phone: "01386 840330",
      email: "weddings@cotswoldhouse.com",
    },
    {
      name: "Cripps Barn",
      slug: "cripps-barn",
      description: "A stunning stone barn wedding venue in the heart of the Cotswolds. Features exposed beams, countryside views, and flexible spaces. Licensed for ceremonies with capacity for up to 200 guests. Blank canvas for your perfect day.",
      category: "Wedding",
      capacity: 200,
      address: "Bibury Road, Cirencester GL7 5NH",
      latitude: "51.7500",
      longitude: "-1.8833",
      amenities: JSON.stringify(["Licensed for ceremonies", "Barn venue", "Countryside views", "Flexible layout", "Parking", "Catering kitchen"]),
      pricing: "Venue hire from £4,500",
      imageUrl: "/images/countryside-walk.jpg",
      website: "https://www.crippsbarn.co.uk",
      phone: "01285 740777",
      email: "info@crippsbarn.co.uk",
      featured: true,
    },
    {
      name: "The Great Tythe Barn",
      slug: "great-tythe-barn",
      description: "A magnificent 14th-century stone barn in Tetbury offering a unique wedding venue. Features original beams, stone walls, and beautiful gardens. Licensed for ceremonies with capacity for up to 150 guests. Historic charm with modern facilities.",
      category: "Wedding",
      capacity: 150,
      address: "Tetbury, Gloucestershire GL8 8TN",
      latitude: "51.6333",
      longitude: "-2.1667",
      amenities: JSON.stringify(["Licensed for ceremonies", "Historic barn", "Gardens", "Parking", "Catering facilities", "Accommodation nearby"]),
      pricing: "Venue hire from £3,800",
      imageUrl: "/images/countryside-walk.jpg",
      website: "https://www.thegreattythebarn.co.uk",
      phone: "01666 505050",
      email: "info@thegreattythebarn.co.uk",
    },
    {
      name: "Cheltenham Racecourse",
      slug: "cheltenham-racecourse-venue",
      description: "A prestigious conference and events venue with stunning views of the Cotswold Hills. Offers flexible event spaces for corporate meetings, conferences, exhibitions, and celebrations. Capacity from 10 to 3,000 guests. Award-winning facilities.",
      category: "Conference",
      capacity: 3000,
      address: "Prestbury Park, Cheltenham GL50 4SH",
      latitude: "51.9333",
      longitude: "-2.0500",
      amenities: JSON.stringify(["Conference facilities", "Exhibition space", "Catering", "AV equipment", "Parking", "Accommodation nearby"]),
      pricing: "Day delegate rates from £45",
      imageUrl: "/images/countryside-walk.jpg",
      website: "https://www.cheltenham.co.uk/events",
      phone: "01242 513014",
      email: "events@cheltenham.co.uk",
      featured: true,
    },
    {
      name: "Cowley Manor",
      slug: "cowley-manor-venue",
      description: "A contemporary country house hotel offering unique event and wedding spaces. Features modern design, spa facilities, and beautiful grounds. Perfect for intimate weddings, corporate retreats, and celebrations. Capacity for up to 100 guests.",
      category: "Wedding",
      capacity: 100,
      address: "Cowley, Cheltenham GL53 9NL",
      latitude: "51.8167",
      longitude: "-2.0333",
      amenities: JSON.stringify(["Licensed for ceremonies", "Spa", "Accommodation", "Modern design", "Catering", "Gardens"]),
      pricing: "Wedding packages from £10,000",
      imageUrl: "/images/manor-house.jpg",
      website: "https://www.cowleymanor.com/weddings",
      phone: "01242 870900",
      email: "weddings@cowleymanor.com",
    },
    {
      name: "Hyde House",
      slug: "hyde-house-venue",
      description: "An elegant Cotswold manor house wedding venue near Stow-on-the-Wold. Offers exclusive use, beautiful gardens, and stunning interiors. Licensed for ceremonies with capacity for up to 150 guests. Perfect for romantic country weddings.",
      category: "Wedding",
      capacity: 150,
      address: "Hyde, Stow-on-the-Wold GL54 1ER",
      latitude: "51.9167",
      longitude: "-1.7000",
      amenities: JSON.stringify(["Licensed for ceremonies", "Exclusive use", "Gardens", "Accommodation", "Catering", "Wedding planning"]),
      pricing: "Wedding packages from £9,000",
      imageUrl: "/images/manor-house.jpg",
      website: "https://www.hydehouse.co",
      phone: "01451 860000",
      email: "info@hydehouse.co",
    },
    {
      name: "Kingscote Barn",
      slug: "kingscote-barn",
      description: "A beautiful stone barn wedding venue with countryside views and flexible spaces. Features exposed beams, modern facilities, and outdoor ceremony area. Licensed for ceremonies with capacity for up to 200 guests. Award-winning venue.",
      category: "Wedding",
      capacity: 200,
      address: "Kingscote, Tetbury GL8 8YA",
      latitude: "51.6833",
      longitude: "-2.2167",
      amenities: JSON.stringify(["Licensed for ceremonies", "Barn venue", "Outdoor ceremony", "Countryside views", "Parking", "Catering"]),
      pricing: "Venue hire from £4,200",
      imageUrl: "/images/countryside-walk.jpg",
      website: "https://www.kingscotebarn.co.uk",
      phone: "01453 860420",
      email: "info@kingscotebarn.co.uk",
    },
  ]);

  console.log("✅ Cotswolds seed completed successfully!");
}

seed()
  .catch((error) => {
    console.error("❌ Seed failed:", error);
    process.exit(1);
  })
  .finally(() => {
    process.exit(0);
  });
